### ISSUE TITLE
Accepting raw POST upload

### ISSUE THREAD

**Issue by czak** [RaVbaker/uploader-server-go#1]
I'd like to send the file via a raw POST upload (i.e. non-multipart).

Essentially I'd like this to work:

```
curl -XPOST http://localhost:8080/upload/ --data-binary @sample.png
```

Can you add support for this? Imgur actually supports **both** formats. I don't think that's necessary for now.
### Why?

Constructing a `multipart/form-data` request in Cocoa is a PITA, but raw uploads are relatively simple.

**Comment by RaVbaker** [comment]
Decided that we won't do it for now.
