### ISSUE TITLE
Configurable hostname

### ISSUE THREAD

**Issue by czak** [RaVbaker/uploader-server-go#3]
I'm now running the server on a VPS.
The public address is neither `localhost` nor `8080`.
However, the `link` returned after the upload is still `http://localhost:8080/image/ba682fcc5026599799eaf72cf9ee23fc-sample.png`.

Please add a way to configure the public hostname + port for correct generation of the URLs.

**Comment by RaVbaker** [comment]
I decided to do it differently. I just display in links the hostname to which request came. But I allow to configure the PORT number via ENV variable. Fixing commit is on way.
